ALTER TABLE Ticket ADD COLUMN CountUnread INTEGER;
ALTER TABLE Account ADD COLUMN countTicket INTEGER;
ALTER TABLE Account ADD COLUMN CountNotify INTEGER;
ALTER TABLE Notify ADD COLUMN Date CHARACTER;